name: Android Firebase App Distribution

on:
  push:
    branches: [ develop ]

jobs:
  distribute:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Update to version')"

    steps:
    # Checkout develop branch
    - uses: actions/checkout@v2
      with:
        key: develop
    - run: |
        echo "${{ secrets.KEYSTORE_FILENAME }}" > release.keystore.asc
        gpg -d --passphrase "${{ secrets.KEYSTORE_FILENAME_PASSHPHRASE }}" --batch release.keystore.asc > app/release.keystore
        
    - uses: actions/setup-node@v1
      with:
        node-version: 12  

    # Set up Ruby and dependencies
    - name: Set up Ruby
      uses: actions/setup-ruby@v1

    - name: Install Dependencies
      run: gem install bundler && bundle install
      
    - name: Install Firebase CLI tools
      run: npm install -g firebase-tools
      
    # Set Git author
    - name: Set Git Author
      run: |
        git config --local user.name "Github Actions CI"
        git config --local user.email "aperezsimon90@gmail.com"
    
    # Runs all unit tests in the application using fastlane
    - name: Run all unit tests
      run: fastlane unit_tests

    # Increment fix number version by one
    - name: Increment fix version
      run: fastlane increment_fix_version

    # Assemble dev flavor with buid type Release
    - name: Assembling Dev flavour Release Build Type
      run: fastlane assemble_dev
      env:
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    # Assemble pro flavor with buid type Release
    - name: Assembling Pro flavour Release Build Type
      run: fastlane assemble_pro
      env:
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    
    # Distribute with firebase distribution dev flavour apk
    - name: Distributing dev flavor to firebase
      run: fastlane dev_firebase_app_distribution
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    
    # Distribute with firebase distribution pro flavour apk
    - name: Distributing pro flavor to firebase
      run: fastlane pro_firebase_app_distribution
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    
    # Commit and push android.gradle file with version updated
    - name: Commit changes with new version
      run: fastlane commit_changes
