name: Android Firebase App Distribution

on:
  push:
    branches: [ develop ]

jobs:
  test:
    name: Running unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Running all unit test in application
      run: bash ./gradlew test --stacktrace
